### ISSUE TITLE
Cannot compile in Ubuntu 16.04

### ISSUE THREAD

**Issue by shakaran** [inkscape/inkscape#26]
Probably related with #25 

	 LANC=C make -j4
	make  all-recursive
	make[1]: se entra en el directorio '/mypath/inkscape'
	Making all in src
	make[2]: se entra en el directorio '/mypath/inkscape/src'
	make  all-am
	make[3]: se entra en el directorio '/mypath/inkscape/src'
	  CXXLD    inkscape
	  CXXLD    inkview
	extension/internal/bitmap/imagemagick.o: In function `Inkscape::Extension::Internal::Bitmap::ImageMagickDocCache::readImage(char const*, Magick::Image*)':
	/mypath/inkscape/src/extension/internal/bitmap/imagemagick.cpp:124: undefined reference to `Magick::Blob::base64(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
	/mypath/inkscape/src/extension/internal/bitmap/imagemagick.cpp:134: undefined reference to `Magick::Image::read(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
	extension/internal/bitmap/imagemagick.o: In function `Inkscape::Extension::Internal::Bitmap::ImageMagick::effect(Inkscape::Extension::Effect*, Inkscape::UI::View::View*, Inkscape::Extension::Implementation::ImplementationDocumentCache*)':
	/mypath/inkscape/src/extension/internal/bitmap/imagemagick.cpp:182: undefined reference to `Magick::Blob::base64[abi:cxx11]()'
	/mypath/inkscape/src/extension/internal/bitmap/imagemagick.cpp:196: undefined reference to `Magick::Image::magick[abi:cxx11]() const'
	extension/internal/image-resolution.o: In function `Inkscape::Extension::Internal::ImageResolution::readmagick(char const*)':
	/mypath/inkscape/src/extension/internal/image-resolution.cpp:404: undefined reference to `Magick::Image::read(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
	/mypath/inkscape/src/extension/internal/image-resolution.cpp:413: undefined reference to `Magick::Image::magick[abi:cxx11]() const'
	collect2: error: ld returned 1 exit status
	Makefile:7231: fallo en las instrucciones para el objetivo 'inkscape'
	make[3]: *** [inkscape] Error 1
	make[3]: *** Se espera a que terminen otras tareas....
	extension/internal/bitmap/imagemagick.o: In function `Inkscape::Extension::Internal::Bitmap::ImageMagickDocCache::readImage(char const*, Magick::Image*)':
	/mypath/inkscape/src/extension/internal/bitmap/imagemagick.cpp:124: undefined reference to `Magick::Blob::base64(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
	/mypath/inkscape/src/extension/internal/bitmap/imagemagick.cpp:134: undefined reference to `Magick::Image::read(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
	extension/internal/bitmap/imagemagick.o: In function `Inkscape::Extension::Internal::Bitmap::ImageMagick::effect(Inkscape::Extension::Effect*, Inkscape::UI::View::View*, Inkscape::Extension::Implementation::ImplementationDocumentCache*)':
	/mypath/inkscape/src/extension/internal/bitmap/imagemagick.cpp:182: undefined reference to `Magick::Blob::base64[abi:cxx11]()'
	/mypath/inkscape/src/extension/internal/bitmap/imagemagick.cpp:196: undefined reference to `Magick::Image::magick[abi:cxx11]() const'
	extension/internal/image-resolution.o: In function `Inkscape::Extension::Internal::ImageResolution::readmagick(char const*)':
	/mypath/inkscape/src/extension/internal/image-resolution.cpp:404: undefined reference to `Magick::Image::read(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
	/mypath/inkscape/src/extension/internal/image-resolution.cpp:413: undefined reference to `Magick::Image::magick[abi:cxx11]() const'
	collect2: error: ld returned 1 exit status
	Makefile:7235: fallo en las instrucciones para el objetivo 'inkview'
	make[3]: *** [inkview] Error 1
	make[3]: se sale del directorio '/mypath/inkscape/src'
	Makefile:5291: fallo en las instrucciones para el objetivo 'all'
	make[2]: *** [all] Error 2
	make[2]: se sale del directorio '/mypath/inkscape/src'
	Makefile:1471: fallo en las instrucciones para el objetivo 'all-recursive'
	make[1]: *** [all-recursive] Error 1
	make[1]: se sale del directorio '/mypath/inkscape'
	Makefile:1127: fallo en las instrucciones para el objetivo 'all'
	make: *** [all] Error 2

This is related with error:

	$ inkscape 
	inkscape: symbol lookup error: inkscape: undefined symbol: _ZN6Magick5Image4readERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

	$ locate libIlmImf
	/usr/lib/x86_64-linux-gnu/libIlmImf-2_2.so.22
	/usr/lib/x86_64-linux-gnu/libIlmImf-2_2.so.22.0.0
	/usr/lib/x86_64-linux-gnu/libIlmImf.a
	/usr/lib/x86_64-linux-gnu/libIlmImf.so
	/usr/lib/x86_64-linux-gnu/libIlmImfUtil-2_2.so.22
	/usr/lib/x86_64-linux-gnu/libIlmImfUtil-2_2.so.22.0.0
	/usr/lib/x86_64-linux-gnu/libIlmImfUtil.a
	/usr/lib/x86_64-linux-gnu/libIlmImfUtil.so
	/usr/lib/x86_64-linux-gnu/x86_64/libIlmImf.so.6

	$ strace -eopen inkscape 2>&1 | tail -n 27
	open("/usr/lib/x86_64-linux-gnu/libwebp.so.5", O_RDONLY|O_CLOEXEC) = 3
	open("/lib/x86_64-linux-gnu/libbz2.so.1.0", O_RDONLY|O_CLOEXEC) = 3
	open("/lib/x86_64-linux-gnu/tls/x86_64/libIlmImf.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
	open("/lib/x86_64-linux-gnu/tls/libIlmImf.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
	open("/lib/x86_64-linux-gnu/x86_64/libIlmImf.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
	open("/lib/x86_64-linux-gnu/libIlmImf.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
	open("/usr/lib/x86_64-linux-gnu/tls/x86_64/libIlmImf.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
	open("/usr/lib/x86_64-linux-gnu/tls/libIlmImf.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
	open("/usr/lib/x86_64-linux-gnu/x86_64/libIlmImf.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
	open("/usr/lib/x86_64-linux-gnu/libIlmImf.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
	open("/lib/tls/x86_64/libIlmImf.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
	open("/lib/tls/libIlmImf.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
	open("/lib/x86_64/libIlmImf.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
	open("/lib/libIlmImf.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
	open("/usr/lib/tls/x86_64/libIlmImf.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
	open("/usr/lib/tls/libIlmImf.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
	open("/usr/lib/x86_64/libIlmImf.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
	open("/usr/lib/libIlmImf.so.6", O_RDONLY|O_CLOEXEC) = 3
	open("/usr/lib/x86_64-linux-gnu/libXau.so.6", O_RDONLY|O_CLOEXEC) = 3
	open("/usr/lib/x86_64-linux-gnu/libXdmcp.so.6", O_RDONLY|O_CLOEXEC) = 3
	open("/lib/x86_64-linux-gnu/libgcrypt.so.20", O_RDONLY|O_CLOEXEC) = 3
	open("/usr/lib/x86_64-linux-gnu/libHalf.so.12", O_RDONLY|O_CLOEXEC) = 3
	open("/usr/lib/x86_64-linux-gnu/libIex-2_2.so.12", O_RDONLY|O_CLOEXEC) = 3
	open("/usr/lib/x86_64-linux-gnu/libIlmThread-2_2.so.12", O_RDONLY|O_CLOEXEC) = 3
	open("/lib/x86_64-linux-gnu/libgpg-error.so.0", O_RDONLY|O_CLOEXEC) = 3
	inkscape: symbol lookup error: inkscape: undefined symbol: _ZN6Magick5Image4readERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
	+++ exited with 127 +++

	$ ls -ialh /usr/lib/libIlmImf.so.6
	2748541 lrwxrwxrwx 1 root root 49 sep 10 03:55 /usr/lib/libIlmImf.so.6 -> /usr/lib/x86_64-linux-gnu/libIlmImf-2_2.so.22.0.0

I am not sure if it is some problem with ImageMagick:

    $ sudo nm -D /usr/lib/libIlmImf.so.6 | grep Magick

This command doesn't list any symbol. So I have a broken system where I cannot install inkscape from deb or even deb package

**Comment by doctormo** [comment]
Thanks for filing this bug report about Inkscape.  This is not an actively monitored bug reporting location for the Inkscape project, however.  The official place to file bug reports is:

    https://bugs.launchpad.net/inkscape/+filebug

For more information on making good bug reports, please read:

    https://inkscape.org/en/contribute/report-bugs/

Thanks again,
Martin Owens
